name: find_dropdown_plus
description: Simple and robust FindDropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization.
version: 1.0.2
homepage: https://github.com/deyvissoneduardo/find_dropdown_plus
repository: https://github.com/deyvissoneduardo/find_dropdown_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  select_dialog: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
 uses-material-design: true